routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('home');
});

Route::group([
    'prefix' => 'categories',
    'middleware' => 'auth',
    'as' => 'category.'
], function () {
    Route::get('', 'CategoryController@index')->name('index');
    Route::get('data', 'CategoryController@getDataCategories')->name('data');
    Route::get('search', 'CategoryController@searchDataCategories')->name('search');
    Route::get('show/{id}', 'CategoryController@show')->name('show');
    Route::get('create', 'CategoryController@create')->name('create');
    Route::post('store', 'CategoryController@store')->name('store');
    Route::get('edit/{id}', 'CategoryController@edit')->name('edit');
    Route::put('update/{id}', 'CategoryController@update')->name('update');
    Route::delete('delete/{id}', 'CategoryController@destroy')->name('destroy');
});


Route::group([
    'prefix' => 'tags',
    'middleware'=>'auth',
    'as' => 'tag.',
],function(){
    route::get('/', 'tagcontroller@index')->name('index'); //hiển thị danh sách tag

    route::get('create', 'tagcontroller@create')->name('create'); //hiển thị form tạo mới 1 tag

    route::post('/', 'tagcontroller@store')->name('store'); //tạo mới tag

    route::get('/show/{id}', 'tagcontroller@show')->name('show'); //hiển thị 1 tag

    route::get('edit/{id}', 'tagcontroller@edit')->name('edit'); //hiển thị form cập nhât 1 tag

    route::get('posts/{id}', 'tagcontroller@posts')->name('posts'); //hiển thị danh sách bài viết


    route::put('/{id}','tagcontroller@update')->name('update'); //cập nhập tag


    route::get('data', 'tagcontroller@getdata')->name('data');


});

Route::group([
    'prefix' => 'posts',
    'as' => 'post.'
], function () {
    Route::get('/', 'PostController@index')->name('index');
    Route::get('create', 'PostController@create')->name('create');
    Route::post('store', 'PostController@store')->name('store');
    Route::get('{id}/edit', 'PostController@edit')->name('edit');
    Route::get('show/{id}', 'PostController@show')->name('show');
    Route::post('update/{id}', 'PostController@update')->name('update');
    Route::delete('delete/{id}', 'PostController@destroy')->name('destroy');
    Route::get('getData', 'PostController@getData')->name('getData');

});


Route::group([
    'middleware' => 'auth',
    'prefix' => 'user',
    'as' => 'user.'
], function () {
    Route::get('/', 'UserController@index')->name('index');
    Route::get('/user-list', 'UserController@user_list')->name('list');
    Route::get('/search', 'UserController@data')->name('data');

    Route::get('create', 'UserController@create')->name('create');
    Route::post('/', 'UserController@store')->name('store');
    Route::put('update/{id}', 'UserController@update')->name('update');
    Route::delete('destroy/{id}', 'UserController@destroy')->name('destroy');
    Route::get('password/{id}', 'UserController@password')->name('password');
    Route::put('change/{id}', 'UserController@change')->name('change');
    Route::get('{id}/edit', 'UserController@edit')->name('edit');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class Tag extends Model
{
    protected $table = 'tags';

    protected $fillable = [
    	'name','slug','user_id',
    ];

    use Notifiable;
    use SoftDeletes;

    public function posts(){
    	return $this->belongsToMany(\App\Post::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreTagRequest;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;

use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

use App\Tag;
use Carbon\Carbon;
use Yajra\Datatables\Datatables;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::orderByRaw('created_at DESC')->get();
        return view('tags.index')->with([
            'tags'=>$tags,
            'categories'=> \App\Category::all()
        ]);
    }

    public function getIndex()
    {
        
        $now = strtotime(Carbon::now('Asia/Ho_Chi_Minh'));
        $created_at = strtotime(\DB::table('tags')->where('id','=',1)->value('created_at'));
        echo Carbon::now('Asia/Ho_Chi_Minh')."<br>";
        echo \DB::table('tags')->where('id','=',1)->value('created_at')."<br>";
        echo "$now <br>";
        echo "$created_at <br>";
        $time = $now - $created_at;
        // if (floor($time/3600)>1) {
        //     $hour = 0;
        //     $time = ($time/3600)>floor($time/3600+0.5)?
        // }
        echo $this->time(\DB::table('tags')->where('id','=',1)->value('created_at'));
    }

    public function time($time){
        $now = strtotime(Carbon::now('Asia/Ho_Chi_Minh'));
        $time = strtotime($time);

        $year = $this->roundNumber(($now - $time)/3600/24/365);
        $month = $this->roundNumber(($now - $time)/3600/24/30);
        $week = $this->roundNumber(($now - $time)/3600/24/7);
        $day = $this->roundNumber(($now - $time)/3600/24);
        $hour = $this->roundNumber(($now - $time)/3600);
        $minute = $this->roundNumber(($now - $time)/60)<1?1:$this->roundNumber(($now - $time)/60);
        $string = "Đã tạo từ ";
        if ($year >=1) {
            return $string.$year." năm trước";
        }elseif($month >=1){
            return $string.$month." tháng trước";
        }elseif($week>=1){
            return $string.$week." tuần trước";
        }elseif($day>=1){
            if($day == 1){
                return $string."hôm qua";
            }
            return $string.$day." ngày trước";
        }else{
            return $string.$minute." phút trước";
        }
    }

    public function roundNumber($number){
        if ($number<1) {
            return $number;
        }
        $floor = floor($number);
        $number = $number<($floor+0.5)?$floor:$floor+1;
        return $number;
    }

    public function getData(Request $request)
    {
            $tags = Tag::select('id','name','slug','created_at');
            if($request->has('name')){
                $tags = $tags->where('name','like',"%" . $request->get('name') . "%");
            }
            if($request->has('slug')){
                $tags = $tags->where('slug','like',"%" . $request->get('slug') . "%");
            }
            return DataTables::of($tags)
            ->editColumn('created_at', function ($tag){
                return TagController::time(\DB::table('tags')->where('id','=',$tag->id)->value('created_at'));
            })
            ->addColumn('action', function ($tag) {
                return '<a  onclick="event.preventDefault();showTag('. $tag->id .');" href="#" class="btn btn-success show open-modal" data-toggle="tooltip" title="Xem chi tiết">
                            <i class="fa fa-btn fa-eye"></i>
                        </a>
                        <a  onclick="event.preventDefault();editTagForm('. $tag->id .');" href="#" class="btn btn-warning edit open-modal" data-toggle="tooltip" title="Chỉnh sửa">
                                <i class="fa fa-btn fa-pencil"></i>
                            </a>
                        <a href="'.route('tag.posts' , $tag->id) .'" type="submit" class="btn btn-primary" data-toggle="tooltip" title="Bài viết">
                            <i class="fa fa-clipboard" aria-hidden="true"></i>
                        </a>
                        <a onclick="event.preventDefault();deleteTagForm('. $tag->id .');" href="#" class="delete btn btn-danger" data-toggle="tooltip" title="Xóa"><i class="fa fa-btn fa-trash"></i></a>';
            })
            ->rawColumns(['action'])

            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),
            [
                'name'=>'required|min:2',
                'slug'=>'unique:tags'
            ],
            [
                'required' => ':attribute Không được để trống',
                'min' => ':attribute Không được nhỏ hơn :min kí tự',
                'unique'=>':attribute đã tồn tại',
            ],
            [
                'name' => 'Tên Tag',
                'slug' => 'Đường dẫn Tag',
            ]
        );
        if($request->get('name')!=''){
        $status = Tag::where('name', 'like binary', $request->get('name'))->get();

        if (!count($status) ==null) {
        $validator->after(function ($validator) {
            $validator->errors()->add('name','Tên Tag đã tồn tại');
        });
        }

        }
        if ($validator->fails()) {
            return response()->json([
                'error'    => true,
                'messages' => $validator->errors(),
            ], 422);
        }
        $tag = new Tag();
        $tag->name = $request->get('name');

        $tag->user_id = Auth::user()->id; 

        $tag->save();
        $tag->slug = $request->get('slug')==null?Str::slug($request->get('name').'-'.$tag->id):Str::slug($request->get('slug'));
        $tag->save();
        Session::flash('msg','Tạo mới Tag '.$tag->name.' thành công');
        return response()->json([
            'error' => false,
            'tag'  => $tag,
        ], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function show($id)
    {
        $tag = Tag::findOrFail($id);
        $created_at = date('H:i:s d-m-Y',strtotime($tag->created_at));
        $user = \DB::table('users')->where('id',$tag->user_id)->value('name');
        return response()->json([
            'error' => false,
            'tag'  => $tag,
            'created_at'=>$created_at,
            'user'=>$user
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::findOrFail($id);
        return view('tags.edit')->with([
            'tag'=>$tag,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),
            [
                'name'=>'required|min:2',
                'slug'=>Rule::unique('tags')->ignore($id),
            ],
            [
                'required' => ':attribute Không được để trống',
                'min' => ':attribute Không được nhỏ hơn :min kí tự',
                'unique'=>':attribute đã tồn tại',
            ],
            [
                'name' => 'Tên Tag',
                'slug' => 'Đường dẫn Tag',
            ]
        );
        if($request->get('name')!=''){

        $status = Tag::where('name', 'like binary', $request->get('name'))->where('id','!=',$request->get('tag_id'))->get();
        
        if (count($status) >0) {
        $validator->after(function ($validator) {
            $validator->errors()->add('name','Tên Tag đã tồn tại');
        });

        }
        }
        if ($validator->fails()) {
            return response()->json([
                'error'    => true,
                'messages' => $validator->errors(),
            ], 422);
        }
        $tag = Tag::findOrFail($id);
        $tag->name = $request->get('name');
        $tag->save();
        $tag->slug = $request->get('slug')==null?Str::slug($request->get('name').'-'.$tag->id):Str::slug($request->get('slug'));
        $tag->save();
        Session::flash('msg','Đã cập nhật Tag '.$tag->name);
        return response()->json([
            'error' => false,
            'tag'  => $tag,
        ], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function posts($tagId){
        $tag = Tag::findOrFail($tagId);
        $posts = $tag->posts()->get();
        return view('tags.posts')->with([
            'tag'=>$tag,
            'posts'=>$posts
        ]);
    }

    public function destroy($id)
    {
        $tag = Tag::destroy($id);

        return response()->json([
            'error' => false,
            'tag'  => $tag,
        ], 200);
    }
}

resources/views/tags/create.blade.php
<div class="modal fade" id="addTagModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="frmAddTag">
                <div class="modal-header">
                    <h4 class="modal-title">
                        Tạo mới Tag
                    </h4>
                    <button aria-hidden="true" class="close" data-dismiss="modal" type="button">
                        ×
                    </button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger" id="add-error-bag">
                        <ul id="add-tag-errors" style="display: block">
                        </ul>
                    </div>
                    <div class="form-group">
                        <label>
                            Tên Tag
                        </label>
                        <input class="form-control" name="name" required="" type="text">
                        </input>
                    </div>
                    <div class="form-group">
                        <label>
                            Đường dẫn Tag <span style="color: green">(Không bắt buộc)</span>
                        </label>
                        <input class="form-control" name="slug" required="" type="text">
                        </input>
                    </div>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-default" data-dismiss="modal" type="button" value="Cancel">
                        <button class="btn btn-info" id="btn-add" type="button" value="add">
                            <i class="fa fa-btn fa-plus"></i>Tạo mới Tag
                        </button>
                    </input>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/tags/delete.blade.php
<div class="modal fade" id="deleteTagModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="frmDeleteTag">
                <div class="modal-header">
                    <h4 class="modal-title" id="delete-title" name="title">
                        Xóa Tag
                    </h4>
                    <button aria-hidden="true" class="close" data-dismiss="modal" type="button">
                        ×
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        Bạn có chắc chắn muốn xóa tag này?
                    </p>
                    <p class="text-warning">
                        <small style="color: red">
                            Thao tác này không thể hoàn lại.
                        </small>
                    </p>
                </div>
                <div class="modal-footer">
                    <input id="tag_id" name="tag_id" type="hidden" value="0">
                        <input class="btn btn-default" data-dismiss="modal" type="button" value="Hủy bỏ">
                            <button class="btn btn-danger" id="btn-delete" type="button">
                                Xóa Tag
                            </button>
                        </input>
                    </input>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/tags/edit.blade.php
<div class="modal fade" id="editTagModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="frmEditTag">
                <div class="modal-header">
                    <h4 class="modal-title">
                        Chỉnh sửa Tag
                    </h4>
                    <button aria-hidden="true" class="close" data-dismiss="modal" type="button">
                        ×
                    </button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger" id="edit-error-bag">
                        <ul id="edit-tag-errors" style="display: block">
                        </ul>
                    </div>
                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    @if(Session::has('msg_error'))
                    <div class="alert alert-danger">{{ Session::get('msg_error') }}</div>
                    @endif
                    <div class="form-group">
                        <label>
                            Tên Tag
                        </label>
                        <input class="form-control" name="name" required="" type="text">
                        </input>
                    </div>
                    @error('slug')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <div class="form-group">
                        <label>
                            Đường dẫn Tag
                        </label>
                        <input class="form-control" name="slug" required="" type="text">
                        </input>
                    </div>
                </div>
                <div class="modal-footer">
                    <input id="tag_id" name="tag_id" type="hidden" value="0">
                        <button class="btn btn-info" id="btn-edit" type="button" value="edit">
                            <i class="fa fa-btn fa-plus"></i>Cập nhật Tag
                        </button>
                    </input>
                    </input>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/tags/index.blade.php
@extends('layouts.app')

@section('title')
Danh sách Tag
@endsection

@section('css')

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
<style>
    body {
        font-family: 'Lato';
    }
    .fa-btn {
        margin-right: 1px;
    }
    .task-table tbody tr td:nth-child(2){
        width: 120px;
    }
    .task-table tbody tr td:nth-child(3){
        width: 100px;
    }
    .add-mb{
        margin-bottom: 2%;
    }
    .swal-title{
        font-family: auto;
    }
    .fade.in {
        opacity: 1;
    }
    .modal.fade .modal-dialog {
        transform: translate(0, 0px);
    }
    .modal.fade{
    }
    .modal-backdrop.in {
        filter: alpha(opacity=50);
        opacity: .5;
    }
</style>
@endsection

@section('script')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script type="text/javascript">
    @if(Session::has('msg'))

    $(function msg(){
        swal("{{ Session::get('msg') }}", " ", "success");
    })

    @endif
</script>
<script type="text/javascript" src="{{ asset('js/tag.js') }}"></script>
<script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script>
$(function(){
    function dataTable(name = '' , slug = ''){
        var myTable = $('#tags-table').DataTable({
            processing: true,
            serverSide: true,
            searching:true,
            destroy:true,
            ajax: {
                "url"  : '{!! route('tag.data') !!}',
                "data" : {
                    "name" : name,
                    "slug" : slug,
                },
            },
            columns: [
                { data: 'id', name: 'id' },
                { data: 'name', name: 'name' },
                { data: 'slug', name: 'slug' },
                { data: 'created_at', name: 'created_at'},
                { data: 'action', name: 'action', orderable: false, searchable: false },
            ]
        })
    }
    dataTable();
    $('.search').on('change', function(e){
      e.preventDefault();
      var name = $('#search_name').val();
      var slug = $('#search_slug').val();
        $.ajax({
            url: '{!! route('tag.data') !!}',
            data: {
                name : name,
                slug : slug,
            },
            success: function (response) {
                dataTable(name, slug);
            },
            error: function (error) {
                console.log('error');
            }
        })
    })
    $("#btn-add").click(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $.ajax({
            type: 'POST',
            url: '/tags',
            data: {
                name: $("#frmAddTag input[name=name]").val(),
                slug: $("#frmAddTag input[name=slug]").val(),
            },
            dataType: 'json',
            success: function(data) {
                $('#frmAddTag').trigger("reset");
                $("#frmAddTag .close").click();
                dataTable();
                swal("Tạo mới thành công", " ", "success");
            },
            error: function(data) {
                var errors = $.parseJSON(data.responseText);
                $('#add-tag-errors').html('');
                $.each(errors.messages, function(key, value) {
                    $('#add-tag-errors').append('<li>' + value + '</li>');
                });
                $("#add-error-bag").show();
            }
        });
    });
    $("#btn-edit").click(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $.ajax({
            type: 'PUT',
            url: '/tags/' + $("#frmEditTag input[name=tag_id]").val(),
            data: {
                name: $("#frmEditTag input[name=name]").val(),
                slug: $("#frmEditTag input[name=slug]").val(),
            },
            dataType: 'json',
            success: function(data) {
                $('#frmEditTag').trigger("reset");
                $("#frmEditTag .close").click();
                dataTable();
                swal("Cập nhật thành công", " ", "success");
            },
            error: function(data) {
                var errors = $.parseJSON(data.responseText);
                $('#edit-tag-errors').html('');
                $.each(errors.messages, function(key, value) {
                    $('#edit-tag-errors').append('<li>' + value + '</li>');
                });
                $("#edit-error-bag").show();
            }
        });
    });
    $("#btn-delete").click(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $.ajax({
            type: 'DELETE',
            url: '/tags/' + $("#frmDeleteTag input[name=tag_id]").val(),
            dataType: 'json',
            success: function(data) {
                $("#frmDeleteTag .close").click();
                dataTable();
                swal("Xóa thành công", " ", "success");
            },
            error: function(data) {
                console.log(data);
            }
        });
    });
})
</script>
@endsection

@section('header')
@include('layouts.header')
@endsection


@section('content')

<div class="container">
    <div class="row justify-content-center" style="display: block;width: 65%;margin: auto;">

        <!-- Current Tasks -->
        <a  onclick="event.preventDefault();addTagForm();" href="#" class="btn btn-success add-mb" data-toggle="modal">
            <i class="fa fa-plus"> </i> Thêm mới Tag
        </a>
        <div class="card">
            <div class="card-header">
                Danh sách Tag
            </div>

            <div class="card-body">
                <table class="table table-striped tag-table" id="tags-table">
                    <thead>
            <tr>
                <th style="padding-bottom: 25px;">Id</th>
                <th>Tên thẻ <input type="text" class="search" id="search_name" style="width: 125px" placeholder="Lọc theo tên"></th>
                <th>Đường dẫn <input type="text" class="search" id="search_slug" style="width: 125px" placeholder="Lọc theo slug"></th>
                <th style="padding-bottom: 25px;">Thời gian tạo</th>
                <th style="padding-bottom: 25px;">Thao tác</th>
            </tr>
        </thead>
                </table>
            </div>
        </div>
    </div>
    @include('tags.show')
    @include('tags.create')
    @include('tags.edit')
    @include('tags.delete')
</div>
@endsection

resources/views/tags/posts.blade.php
@extends('layouts.app')

@section('title')
Danh sách bài viết
@endsection

@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>
<style>
    body {
        font-family: 'Lato';
    }
    .fa-btn {
        margin-right: 1px;
    }
    .task-table tbody tr td:nth-child(2){
        width: 120px;
    }
    .task-table tbody tr td:nth-child(3){
        width: 100px;
    }
    .add-mb{
        margin-bottom: 2%;
    }
    .swal-title{
        font-family: auto;
    }
</style>
@endsection

@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script type="text/javascript">
    @if(Session::has('msg'))

    $(function msg(){
        swal("{{ Session::get('msg') }}", " ", "success");
    })

@endif
</script>
@endsection

@section('header')
@include('layouts.header')
@endsection


@section('content')

<div class="container">
    <div class="row justify-content-center" style="display: block;width: 65%;margin: auto;">

        <!-- Current Tasks -->
        <a href="{{ route('tag.index') }}" class="btn btn-success add-mb">
            <i class="fa fa-arrow-left" aria-hidden="true"></i> Danh sách Tag
        </a>
        <div class="card">
            <div class="card-header">
                Bài viết của Tag "{{ $tag->name }}"
            </div>

            <div class="card-body">
                <table class="table table-striped task-table">
                    <thead>
                    <th>STT</th>
                    <th>Tên Tag</th>
                    <th colspan="4">Thao tác</th>
                    </thead>
                    <tbody>
                    @foreach($posts as $key => $post)
                        <tr>
                            <td>{{$key+1}} </td>
                        <td class="table-text">
                            <div><a href="{{ route('post.show',$post->id) }}">
                                {{$post->title}}
                            </a></div>
                        </td>
                        
                        <td>
                            <a href="{{ route('post.show' , $post->id) }}" class="btn btn-success" style="width: 140px;">
                                <i class="fa fa-btn fa-eye"></i> Xem chi tiết
                            </a>
                        </td>
                        
                        <td>
                            <a href="{{ route('post.edit' , $post->id) }}" type="submit" class="btn btn-warning">
                                <i class="fa fa-btn fa-pencil"></i> Chỉnh sửa
                            </a>
                        </td>
                        <!-- Task Delete Button -->
                        <td>
                            <form action="{{ route('post.destroy' , $post->id) }}" method="POST">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <button type="submit" class="btn btn-danger">
                                    <i class="fa fa-btn fa-trash"></i> Xóa
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tags/show.blade.php
<div class="modal fade" id="showTagModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="showTag">
                <div class="modal-header">
                    <h4 class="modal-title">
                        Chi tiết Tag
                    </h4>
                    <button aria-hidden="true" class="close" data-dismiss="modal" type="button">
                        ×
                    </button>
                </div>
                <div class="card-body">
                <table class="table table-striped">
                    <thead>
                    <th style="width: 100px">Thuộc tính</th>
                    <th>Thông tin</th>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Tên thẻ: </td>
                        <td id="name"></td>
                    </tr>
                    <tr>
                        <td>Đường dẫn: </td>
                        <td id="slug"></td>
                    </tr>
                    <tr>
                        <td>Người tạo: </td>
                        <td id="user"></td>
                    </tr>
                    <tr>
                        <td>Ngày tạo: </td>
                        <td id="created_at"></td>
                    </tr>
                    </tbody>
                </table>
            </div>

            </form>
        </div>
    </div>
</div>