routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('home');
});

Route::group([
    'prefix' => 'categories',
    'middleware' => 'auth',
    'as' => 'category.'
], function () {
    Route::get('', 'CategoryController@index')->name('index');
    Route::get('data', 'CategoryController@getDataCategories')->name('data');
    Route::get('search', 'CategoryController@searchDataCategories')->name('search');
    Route::get('show/{id}', 'CategoryController@show')->name('show');
    Route::get('create', 'CategoryController@create')->name('create');
    Route::post('store', 'CategoryController@store')->name('store');
    Route::get('edit/{id}', 'CategoryController@edit')->name('edit');
    Route::put('update/{id}', 'CategoryController@update')->name('update');
    Route::delete('delete/{id}', 'CategoryController@destroy')->name('destroy');
});


Route::group([
    'prefix' => 'tags',
    'middleware'=>'auth',
    'as' => 'tag.',
],function(){
    route::get('/', 'tagcontroller@index')->name('index'); //hiển thị danh sách tag

    route::get('create', 'tagcontroller@create')->name('create'); //hiển thị form tạo mới 1 tag

    route::post('/', 'tagcontroller@store')->name('store'); //tạo mới tag

    route::get('/show/{id}', 'tagcontroller@show')->name('show'); //hiển thị 1 tag

    route::get('edit/{id}', 'tagcontroller@edit')->name('edit'); //hiển thị form cập nhât 1 tag

    route::get('posts/{id}', 'tagcontroller@posts')->name('posts'); //hiển thị danh sách bài viết


    route::put('/{id}','tagcontroller@update')->name('update'); //cập nhập tag


    route::get('data', 'tagcontroller@getdata')->name('data');


});

Route::group([
    'prefix' => 'posts',
    'as' => 'post.'
], function () {
    Route::get('/', 'PostController@index')->name('index');
    Route::get('create', 'PostController@create')->name('create');
    Route::post('store', 'PostController@store')->name('store');
    Route::get('{id}/edit', 'PostController@edit')->name('edit');
    Route::get('show/{id}', 'PostController@show')->name('show');
    Route::post('update/{id}', 'PostController@update')->name('update');
    Route::delete('delete/{id}', 'PostController@destroy')->name('destroy');
    Route::get('getData', 'PostController@getData')->name('getData');

});


Route::group([
    'middleware' => 'auth',
    'prefix' => 'user',
    'as' => 'user.'
], function () {
    Route::get('/', 'UserController@index')->name('index');
    Route::get('/user-list', 'UserController@user_list')->name('list');
    Route::get('/search', 'UserController@data')->name('data');

    Route::get('create', 'UserController@create')->name('create');
    Route::post('/', 'UserController@store')->name('store');
    Route::put('update/{id}', 'UserController@update')->name('update');
    Route::delete('destroy/{id}', 'UserController@destroy')->name('destroy');
    Route::get('password/{id}', 'UserController@password')->name('password');
    Route::put('change/{id}', 'UserController@change')->name('change');
    Route::get('{id}/edit', 'UserController@edit')->name('edit');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class Post extends Model
{
    use Notifiable;
    use SoftDeletes;

    protected $table = 'posts';

    protected $fillable = [
    	'title', 'description', 'content', 'status', 'thumbnail', 'view_count', 'category_id', 'slug', 'user_id'
    ];

    public function posts(){
    	return $this->belongsToMany(\App\Tag::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;
use App\Category;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;
use App\Post;
use Yajra\DataTables\Facades\DataTables;

class postController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function getData()
    {
        return DataTables::of(Post::query())->addColumn('action', function ($post) {
            return '<a href="'. route('post.show', $post->id) .'" class="btn btn-xs btn-primary btn-show" data-id = "'.$post->id.'"  style = "margin-right:5px;"><i class="fa fa-eye"></i> Xem chi tiết</a> <a href="'. route('post.edit', $post->id) .'" class="btn btn-xs btn-warning btn-edit" data-id="'.$post->id.'" style = "margin-right:5px;"><i class="fa fa-eye"></i> Chỉnh sửa</a> <a href="'. route('post.destroy', $post->id) .'" data-id="' . $post->id . '" class="btn btn-xs btn-danger btn-delete"><i class="fa fa-times"></i> Delete</a>';
//            return '<a href="' . route('post.show', $post->id) . '" class="btn btn-xs btn-warning">show</a><a href="' . route('post.edit', $post->id) . '" class="btn btn-xs btn-warning">edit<a href="" data-id="' . $post->id . '" class="btn btn-xs btn-danger btn-delete"> Delete</a>';
        })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function index()
    {

        $list_posts=Post::orderBy('id','DESC')->get();
        $list_posts=Post::orderBy('id','DESC')->get();
        $list_posts=Post::all()->sortDesc();
//        dd($list_posts);
        return view('posts.index')->with([
            'list_post' => $list_posts
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!Auth::user()) {
            return redirect('/login');
        }
        $list_category = Category::all();
        $list_stag = Tag::all();
        $tags = '';
        foreach ($list_stag as $tag) $tags .= $tag->name . ',';
//        dd($tags);
        return response()->json([
            'list_category' => $list_category,
            'tags' => $tags,
            'list_tags' => $list_stag
        ],200);
//        return view('posts.create')->with([
//            'list_category' => $list_category,
//            'tags' => $tags,
//            'list_tags' => $list_stag
//        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        var_dump($request->all());
//        die($request->allFiles());
        $post = new Post();
        $thumbnail = $request->file('thumbnail');
        $thumbnail->store('image');
        $name = date('YmdHis') . "." . $thumbnail->getClientOriginalExtension();
        $thumbnail->move('images', $name);
        $post->thumbnail = $name;
        $post->title = $request->get('title');
        $post->content = $request->get('content');
        $post->category_id = 1;
        $post->description = $request->get('description');
        $post->view_count = 0;
        $post->status = 0;
        $post->user_id = Auth::user()->id;
        $post->slug = Str::slug($post->description) . time();

        $tags = explode(',', $request->tags);
        $post->save();
        for ($i = 0; $i < count($tags); $i++) {
            $tag = Tag::all()->where('name', $tags[$i])->first();
            if ($tag == null) {
                //neu tag chua co thi tao tag moi
                $new_tag = new Tag();
                $new_tag->name = $tags[$i];
                $new_tag->slug = Str::slug($tags[$i]) . time();
                $new_tag->user_id = $post->user_id;
                $new_tag->save();
                //sau do thi tao quan he tren bang phu
                \DB::table('post_tag')->insert(
                    ['post_id' => $post->id, 'tag_id' => $new_tag->id]
                );
            } else {
                //tag co san thi tao quan he tren bang phu
                \DB::table('post_tag')->insert(
                    ['post_id' => $post->id, 'tag_id' => $tag->id]
                );
            }
        }
//        if($save) return response()->json('success',true);
    }


    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        if ($post == null) {
            return abort(404);
        }
        $list_tag = \DB::table('post_tag')->where('post_id', $post->id)->get();
//        dd($list_tag);
        return json_encode($post);
//        return view('posts.show')->with([
//            'post' => $post,
//            'category' => Category::find($post->category_id),
//            'list_tag' => $list_tag
//        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        if ($post == null) {
            return abort(404);
        }
        if (Gate::allows('update-post', $post)) {
            //tags la xau tag1,tag2,..tagn
            $list_stag = Tag::all();
            //list_stag la mang gom ta ca cac tag
            //list_tag la mang gom cac tag cua bai viet

            $list_tag = DB::table('post_tag')->where('post_id', $post->id)->get();
            $tags = '';
            foreach ($list_tag as $tag) $tags .= Tag::find($tag->tag_id)->name . ',';
            $tags = trim($tags, ',');

            $list_category = Category::all();

            return response()->json([
                'post' => $post,
                'list_category' => $list_category,
                'list_tag' => $list_tag,
                'list_tags' => $list_stag,
                'tags' => $tags
            ],200);

        } else {
            return abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::find($id);
        if ($post == null) {
            return abort(404);
        }

        if (Gate::allows('update-post', $post)) {
            if ($request->thumbnail != null) {
                $thumbnail = $request->file('thumbnail');
                $thumbnail->store('image');
                $name = date('YmdHis') . "." . $thumbnail->getClientOriginalExtension();
                $thumbnail->move('images', $name);
                $post->thumbnail = $name;
            }
            $post->title = $request->get('title');
            $post->content = $request->get('content');
            $post->category_id = $request->get('category_id');
            $post->description = $request->get('description');
            $post->slug = Str::slug($post->description) . time();

            //xoa tat ca cac lien ket voi cac tag ban dau
            DB::table('post_tag')->where('post_id', $post->id)->delete();

            //tao lai lien ket voi cac tag moi
//        dd($request->tags);
            $tags = explode(',', $request->tags);
            $post->save();
            for ($i = 0; $i < count($tags); $i++) {
                $tag = Tag::all()->where('name', $tags[$i])->first();
                if ($tag == null) {
                    //neu tag chua co thi tao tag moi
                    $new_tag = new Tag();
                    $new_tag->name = $tags[$i];
                    $new_tag->slug = Str::slug($tags[$i]) . time();
                    $new_tag->user_id = $post->user_id;
                    $new_tag->save();
                    //sau do thi tao quan he tren bang phu
                    \DB::table('post_tag')->insert(
                        ['post_id' => $post->id, 'tag_id' => $new_tag->id]
                    );
                } else {
                    //tag co san thi tao quan he tren bang phu
                    \DB::table('post_tag')->insert(
                        ['post_id' => $post->id, 'tag_id' => $tag->id]
                    );
                }
            }
            return $this->show($post->id);
        } else return abort(403, 'Unauthorized action.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $post = Post::find($id);
        $post->delete();
        $post=Post::where('id',$id);
        $post->delete();
        return redirect()->back();
        $post=Post::find($id);
        if($post==null){
            return abort(404);
        }
        if(Gate::allows('delete-post',$post)) {
            $post->delete();
            return redirect()->back();
        }else return abort(403, 'Unauthorized action.');
    }
}

resources/views/posts/create.blade.php
<div class="modal fade" id="modalCreate"style="padding-top: 200px;background-color: #21252975;">
    <div class="modal-dialog">
        <div class="modal-content" style="width: 900px;right: 175px;">

            <div class="card col-sm-12">
                <div class="card-heading">
                    Thêm mới bài viết

                </div>

                <div class="card-body">
                    <!-- Display Validation Errors -->

                    <!-- New Task Form -->
                    <form id="create_form" method="POST" class="form-horizontal" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <!-- Task Name -->
                        <div class="form-group row">
                            <label for="task-name" class="col-sm-2 control-label" style="float: left">Tiêu đề</label>

                            <div class="col-sm-9">
                                <input type="text" name="title" class="form-control" value="{{ old('name') }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="task-name" class="col-sm-2 control-label">Mô tả bài viết</label>

                            <div class="col-sm-9">
                                <input type="text" name="description"  class="form-control" value="{{ old('name') }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="task-name" class="col-sm-2 control-label" id="category_id">Chọn danh mục</label>
                            <div class="col-sm-9">
                                <select name="category_id" class="form-control categories custom-select" id="category_id" required="required">

                                </select>
                            </div>

                        </div>


                        <div class="form-group row">
                            <label for="task-name" class="col-sm-2 control-label">Nội dung bài viết</label>

                            <div class="col-sm-9">
                                <textarea id="summernote" name="content"></textarea>
                            </div>

                        </div>
                        <div class="form-group row">
                            <label for="exampleInputFile" class="col-sm-2 control-label" >Hình ảnh mô tả bài viết</label>
                            <div class="input-group col-sm-9">
                                <div class="custom-file">
                                    <input type="file" name="thumbnail">
{{--                                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>--}}
                                </div>
                            </div>

                        </div>

                        <div class="form-group row">
                            <label for="exampleInputFile" class="col-sm-2 control-label" >Tags</label>
                            <div class="input-group col-sm-9">
                                <div class="custom-file" style="width: auto!important;">
                                    <input id="form-tags-4" name="tags" type="text" value="" style="width: auto!important;">
                                </div>
                            </div>
                        </div>
                        <!-- Add Task Button -->
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <button type="button" class="btn btn-default create_save" >
                                    <i class="fa fa-btn fa-plus "></i>Lưu bài viết
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div></div></div>

resources/views/posts/create1.blade.php
@extends('layouts.app')

@section('title')
    Tạo bài viết
@endsection

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{{asset('src/jquery.tagsinput-revisited.css')}}" />

    <style>

        html {
            height: 100%;
            margin: 0;
        }

        body {
            min-height: 100%;
            /*font-family: sans-serif;*/
            padding: 20px;
            margin: 0;
        }
        /*.tag {*/
        /*    position: relative;*/
        /*    background: #556270;*/
        /*    display: block;*/
        /*    max-width: 100%;*/
        /*    word-wrap: break-word;*/
        /*    color: #fff;*/
        /*    padding: 5px 30px 5px 5px;*/
        /*    border-radius: 2px;*/
        /*    margin: 0 5px 5px 0;*/
        /*}*/

        label {
            display: block;
            padding: 20px 0 5px 0;
        }
    </style>
    <style>
        body {
            font-family: 'Lato';
        }
        .fa-btn {
            margin-right: 1px;
        }
        .task-table tbody tr td:nth-child(2){
            width: 120px;
        }
        .task-table tbody tr td:nth-child(3){
            width: 100px;
        }
        #view-create{
            margin-top: 5%;
        }
        .add-mb{
            margin-bottom: 2%;
        }
    </style>
@endsection

@section('script')
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="{{asset('src/jquery.tagsinput-revisited.js')}}"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#summernote').summernote({
                placeholder: 'Enter content....',
                tabsize: 2,
                height: 200,
                minHeight: 100,
                maxHeight: 300,
                focus: true,
                toolbar: [
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['font', ['strikethrough', 'superscript', 'subscript']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                    ['table', ['table']],
                    ['insert', ['link', 'picture', 'video']],
                    ['view', ['fullscreen', 'codeview', 'help']],
                ],
                popover: {
                    image: [
                        ['image', ['resizeFull', 'resizeHalf', 'resizeQuarter', 'resizeNone']],
                        ['float', ['floatLeft', 'floatRight', 'floatNone']],
                        ['remove', ['removeMedia']]
                    ],
                    link: [
                        ['link', ['linkDialogShow', 'unlink']]
                    ],
                    table: [
                        ['add', ['addRowDown', 'addRowUp', 'addColLeft', 'addColRight']],
                        ['delete', ['deleteRow', 'deleteCol', 'deleteTable']],
                    ],
                    air: [
                        ['color', ['color']],
                        ['font', ['bold', 'underline', 'clear']],
                        ['para', ['ul', 'paragraph']],
                        ['table', ['table']],
                        ['insert', ['link', 'picture']]
                    ]
                },
                codemirror: {
                    theme: 'monokai'
                }
            });
        });
    </script>
    <script type="text/javascript">
        // @php($list_tag = \Illuminate\Support\Facades\DB::table('post_tag')->where('post_id', $post->id)->get())
        $(document).ready(function() {
            $('#form-tags-4').tagsInput({
                'autocomplete': {
                    source: [
                        @foreach($list_tag as $tag)
                        '{{$tag->name}}',
                        @endforeach
                    ]
                }
            });
        });
    </script>
@endsection



@section('content')
    <div class="container"><a href="{{ route('post.index') }}" class="btn btn-success add-mb" style="    margin-left: 128px !important;">
            <i class="fa fa-arrow-left"> </i> Danh sách bài viết
        </a>
<div class="row justify-content-center" id="view-create">

    <div class="card col-sm-9">
        <div class="card-heading">
            Thêm mới bài viết

        </div>

        <div class="card-body">
            <!-- Display Validation Errors -->

            <!-- New Task Form -->
            <form action="{{ route('post.store') }}" method="POST" class="form-horizontal" enctype="multipart/form-data">
            {{ csrf_field() }}

            <!-- Task Name -->
                <div class="form-group row">
                    <label for="task-name" class="col-sm-3 control-label" style="float: left">Tiêu đề</label>

                    <div class="col-sm-6">
                        <input type="text" name="title" id="task-name" class="form-control" value="{{ old('name') }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="task-name" class="col-sm-3 control-label">Mô tả bài viết</label>

                    <div class="col-sm-6">
                        <input type="text" name="description" id="task-name" class="form-control" value="{{ old('name') }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="task-name" class="col-sm-3 control-label">Chọn danh mục</label>
                    <div class="col-sm-6">
                        <select name="category_id" class="form-control categories">
                            @foreach($list_category as $category)
<!--                                <option value="{{$category->id}}">{{$category->name}}</option>-->
                            @endforeach

                        </select>
                    </div>
                    @if($errors->has('parent_id'))
<!--                        <div class="error">{{ $errors->first('parent_id') }}</div>-->
                    @endif
                </div>


                <div class="form-group row">
                    <label for="task-name" class="col-sm-3 control-label">Nội dung bài viết</label>

                    <div class="col-sm-9">
                        <textarea id="summernote" name="content"></textarea>
                    </div>

                </div>
                <div class="form-group row">
                    <label for="exampleInputFile" class="col-sm-3 control-label" >Hình ảnh mô tả bài viết</label>
                    <div class="input-group col-sm-6">
                        <div class="custom-file">
                            <input type="file" name="thumbnail" class="custom-file-input" id="thumbnail" value="">
                            <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                    </div>

                </div>
                <div class="form-group row">
                    <label for="exampleInputFile" class="col-sm-3 control-label" >Tags</label>
                    <div class="input-group col-sm-6">
                        <div class="custom-file">
                            <input id="form-tags-4" name="tags" type="text" value="">
                        </div>
                    </div>
                </div>
                <!-- Add Task Button -->
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-6">
                        <button type="submit" class="btn btn-default">
                            <i class="fa fa-btn fa-plus"></i>Lưu bài viết
                        </button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div></div>

    @endsection

resources/views/posts/edit.blade.php
<div class="modal fade" id="modalEdit"style="padding-top: 200px;background-color: #21252975;">
    <div class="modal-dialog">
        <div class="modal-content" style="width: 900px;right: 175px;">

            <div class="card col-sm-12">
                <div class="card-heading">
                    Chỉnh sửa bài viết

                </div>

                <div class="card-body">
                    <!-- Display Validation Errors -->

                    <!-- New Task Form -->
                    <form  method="POST" class="form-horizontal" enctype="multipart/form-data">
                    {{ csrf_field() }}

                    <!-- Task Name -->
                        <div class="form-group row">
                            <label  for="task-name" class="col-sm-2 control-label" style="float: left">Tiêu đề</label>

                            <div class="col-sm-6">
                                <input type="text" name="title" class="form-control title" value="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="task-name" class="col-sm-2 control-label">Mô tả bài viết</label>

                            <div class="col-sm-6">
                                <input type="text" name="description" id="description" class="form-control description" value="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="task-name" class="col-sm-2 control-label">Chọn danh mục</label>
                            <div class="col-sm-6">
                                <select class="categories" name="category_id" class="form-control" required="required">

                                </select>
                            </div>

                        </div>


                        <div class="form-group row">
                            <label for="task-name" class="col-sm-2 control-label">Nội dung bài viết</label>

                            <div class="col-sm-9">
                                <textarea  name="content" required="required"></textarea>
                            </div>

                        </div>
                        <div class="form-group row">
                            <img src="" alt="" style="width: 90%; height: auto">
                            <label for="exampleInputFile" class="col-sm-2 control-label" >Hình ảnh mô tả bài viết</label>
                            <div class="input-group col-sm-6">

                                <div class="ccol-sm-6">
                                    <input type="file" name="thumbnail" class="thumbnail" id="thumbnail" value="">
{{--                                    <label class="" for="exampleInputFile">Choose file</label>--}}
                                </div>
                            </div>

                        </div>
                        <div class="form-group row">
                            <label for="exampleInputFile" class="col-sm-2 control-label" >Tags</label>
                            <div class="input-group col-sm-6">
                                <div class="custom-file">
                                    <input class="form-tags-2" name="tags" type="text" value="" >
                                </div>
                            </div>
                        </div>
                        <!-- Add Task Button -->
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-6">
                                <button type="button" class="btn edit_save">
                                    <i class="fa fa-btn fa-plus"></i>Lưu bài viết
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div></div></div>

resources/views/posts/show.blade.php
<div class="modal fade" id="show" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="width: 900px;right: 175px;">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img src="" alt="" class="image" style="">
                <h1 class="title"></h1>
                <p class="time"></p>
                <hr>
                <h2 class="description"></h2>
                <span class="content"></span>
                <p class="user"></p>
                <p class="tag"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>