routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('home');
});

Route::group([
    'prefix' => 'categories',
    'middleware' => 'auth',
    'as' => 'category.'
], function () {
    Route::get('', 'CategoryController@index')->name('index');
    Route::get('data', 'CategoryController@getDataCategories')->name('data');
    Route::get('search', 'CategoryController@searchDataCategories')->name('search');
    Route::get('show/{id}', 'CategoryController@show')->name('show');
    Route::get('create', 'CategoryController@create')->name('create');
    Route::post('store', 'CategoryController@store')->name('store');
    Route::get('edit/{id}', 'CategoryController@edit')->name('edit');
    Route::put('update/{id}', 'CategoryController@update')->name('update');
    Route::delete('delete/{id}', 'CategoryController@destroy')->name('destroy');
});


Route::group([
    'prefix' => 'tags',
    'middleware'=>'auth',
    'as' => 'tag.',
],function(){
    route::get('/', 'tagcontroller@index')->name('index'); //hiển thị danh sách tag

    route::get('create', 'tagcontroller@create')->name('create'); //hiển thị form tạo mới 1 tag

    route::post('/', 'tagcontroller@store')->name('store'); //tạo mới tag

    route::get('/show/{id}', 'tagcontroller@show')->name('show'); //hiển thị 1 tag

    route::get('edit/{id}', 'tagcontroller@edit')->name('edit'); //hiển thị form cập nhât 1 tag

    route::get('posts/{id}', 'tagcontroller@posts')->name('posts'); //hiển thị danh sách bài viết


    route::put('/{id}','tagcontroller@update')->name('update'); //cập nhập tag


    route::get('data', 'tagcontroller@getdata')->name('data');


});

Route::group([
    'prefix' => 'posts',
    'as' => 'post.'
], function () {
    Route::get('/', 'PostController@index')->name('index');
    Route::get('create', 'PostController@create')->name('create');
    Route::post('store', 'PostController@store')->name('store');
    Route::get('{id}/edit', 'PostController@edit')->name('edit');
    Route::get('show/{id}', 'PostController@show')->name('show');
    Route::post('update/{id}', 'PostController@update')->name('update');
    Route::delete('delete/{id}', 'PostController@destroy')->name('destroy');
    Route::get('getData', 'PostController@getData')->name('getData');

});


Route::group([
    'middleware' => 'auth',
    'prefix' => 'user',
    'as' => 'user.'
], function () {
    Route::get('/', 'UserController@index')->name('index');
    Route::get('/user-list', 'UserController@user_list')->name('list');
    Route::get('/search', 'UserController@data')->name('data');

    Route::get('create', 'UserController@create')->name('create');
    Route::post('/', 'UserController@store')->name('store');
    Route::put('update/{id}', 'UserController@update')->name('update');
    Route::delete('destroy/{id}', 'UserController@destroy')->name('destroy');
    Route::get('password/{id}', 'UserController@password')->name('password');
    Route::put('change/{id}', 'UserController@change')->name('change');
    Route::get('{id}/edit', 'UserController@edit')->name('edit');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use SoftDeletes;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ChangePasswordRequest;
use App\Http\Requests\UpdateUserRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\Facades\DataTables;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('created_at', 'desc')->paginate(10);
        return view('user.index')->with('users', $users);
    }

    public function user_list()
    {
        $users = User::query();
        return Datatables::of($users)
            ->editColumn('role', function ($user) {
                return $user->role == 1 ? "Admin" : "Member";
            })
            ->editColumn('phone', function ($user) {
                return $user->phone ? $user->phone : "Đang cập nhật";
            })
            ->addColumn('action', function ($user) {
                if (Auth::user()->role == 1 && Auth::user()->id != $user->id)
                    return '<a href="" data-id="' . $user->id . '" class="btn btn-xs btn-warning edit-modal"><i class="fa fa-edit"></i> eidt</a> <a href="" data-id="' . $user->id . '" class="btn btn-xs btn-danger btn-delete"><i class="fa fa-times"></i> Delete</a>';
                elseif (Auth::user()->id == $user->id)
                    return '<a href="" data-id="' . $user->id . '" class="btn btn-xs btn-warning edit-modal"><i class="fa fa-edit"></i> eidt</a>';

            })
            ->make();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return json_encode($user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = Validator::make($request->all(),
            [
                'name' => 'required|min:3|max:50',
                'email' => 'required|email|unique:users,email,' . $id,
                'phone' => 'required'
            ],
            [
                'required' => ':attribute không được để trống',
                'email' => ':attribute không phải email',
                'unique' => ':attribute đã tồn tại',
            ],
            [
                'name' => 'Tên người dùng',
                'phone' => 'Số điện thoại'
            ]
        );

        if ($validate->fails()) {
            return response()->json(['errors' => $validate->errors()], 200);
        }else{
            $user = User::find($id);
            $user->name = $request->get('name');
            $user->email = $request->get('email');
            $user->phone = $request->get('phone');
            $user->role = $request->get('role');
            $user->save();
            return response()->json(['success' => true], 200);
        }




    }

    public function data(Request $request)
    {
        $users = User::select('id', 'name', 'email', 'phone', 'role');
        if ($request->get("key")) {
            if ($request->get('option') == 1) {
                $users = $users->where('name', 'like', "%" . $request->get('key') . "%");
            }
            if ($request->get('option') == 2) {
                $users = $users->where('email', 'like', "%" . $request->get('key') . "%");
            }
            if ($request->get('option') == 3) {
                $users = $users->where('phone', 'like', "%" . $request->get('key') . "%");
            }
        }
        if($request->get("role_option") && $request->get("role_option")!="all" && $request->get("role_option")!="") {
            if ( $request->get('role_option') == 1)
                $users = $users->where('role', $request->get('role_option') );
            else $users = $users->where('role', 0);
        }
        return DataTables::of($users)
            ->editColumn('role', function ($user) {
                return $user->role == 1 ? "Admin" : "Member";
            })
            ->editColumn('phone', function ($user) {
                return $user->phone ? $user->phone : "Đang cập nhật";
            })
            ->addColumn('action', function ($user) {
                if (Auth::user()->role == 1 && Auth::user()->id != $user->id)
                    return '<a href="" data-id="' . $user->id . '" class="btn btn-xs btn-warning edit-modal"><i class="fa fa-edit"></i> eidt</a> <a href="" data-id="' . $user->id . '" class="btn btn-xs btn-danger btn-delete"><i class="fa fa-times"></i> Delete</a>';
                elseif (Auth::user()->id == $user->id)
                    return '<a href="" data-id="' . $user->id . '" class="btn btn-xs btn-warning edit-modal"><i class="fa fa-edit"></i> eidt</a>';

            })
            ->rawColumns(['action'])
            ->make();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        die("a");
    }

    public function password($id)
    {
        $user = User::find($id);
        return view('user.password')->with('user', $user);

    }

    public function change(Request $request)
    {
        $validate = Validator::make($request->all(),
            [
                'password_old'=>'required',
                'password'=>'required|confirmed|min:6',
                'password_confirmation'=>'required'
            ],
            [
                'required' => ':attribute không được để trống',
                'confirmed' => ':attribute không khớp',
                'unique' => ':attribute đã tồn tại',
                'min'=>':attribute phải lớn hơn 6 kí tự'
            ],
            [
                'password-_old'=>'Mật khẩu cũ',
                'password' => 'Mật khẩu mới',
                'password_confirmation'=>'Xác nhận mật khẩu'
            ]
        );

        if ($validate->fails()) {
            return response()->json(['errors' => $validate->errors()], 200);
        }

        $user = Auth::user();
        if (Hash::check($request->get('password_old'), $user->password)) {
            $user->password = Hash::make($request->get('password'));
            $user->save();
            return response()->json(['success' => true], 200);
        } else{
            return response()->json(['error' => 'Mật khẩu cũ không đúng'], 200);
        }
    }
}

resources/views/user/password.blade.php
@extends('layouts.app')



<!-- JavaScripts -->
@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
@endsection

@section('title')
    change password
@endsection

@section('content')
    <
    <div class="container">
        <div class="row justify-content-center">
            <div class="card" style="width: 550px">
                <div class="card-header">
                    <div>
                        Edit User
                    </div>
                </div>

                <div class="card-body">
                    <!-- Display Validation Errors -->

                    <!-- New Task Form -->
                    <form action="{{route('user.change',Auth::user()->id)}}" method="POST" class="form-horizontal">
                    @csrf
                    @method('PUT')

                    <!-- Task Name -->
                        <div class="form-group">
                            <label for="task-name" class="col-sm control-label">Password old</label>

                            <div class="col-sm">
                                <input type="password" name="password-old" class="form-control"
                                       value="">
                                @error('password-old')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>

                        </div>

                        <div class="form-group">
                            <label for="task-name" class="col-sm control-label">Password</label>

                            <div class="col-sm">
                                <input type="password" name="password" class="form-control"
                                       value="">
                                @error('password')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>

                        </div>

                        <div class="form-group">
                            <label for="task-name" class="col-sm control-label">Password confirm</label>

                            <div class="col-sm">
                                <input type="password" name="password_confirmation" class="form-control"
                                       value="">
                                @error('password_confirmation')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>


                        </div>

                        <!-- Add Task Button -->
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-6">
                                <button type="submit" class="btn btn-success">
                                    <i class="fa fa-btn fa-plus"></i>Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/update.blade.php
@extends('layouts.app')

<!-- JavaScripts -->
@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
@endsection

@section('title')
    update
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="card" style="width: 550px">
                <div class="card-header">
                    <div>
                        Edit User
                    </div>
                    @can('password', $user)
                        <div>
                            <form action="{{route('user.password',$user->id)}}" method="GET"
                                  style="margin-right: 5px;">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-btn fa-edit"></i>Change Password
                                </button>
                            </form>
                        </div>
                    @endcan
                </div>

                <div class="card-body">
                    <!-- Display Validation Errors -->

                    <!-- New Task Form -->
                    <form action="{{route('user.update',$user->id)}}" method="POST" class="form-horizontal">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}

                    <!-- Task Name -->
                        <div class="form-group">
                            <label for="task-name" class="col-sm-3 control-label">Name</label>

                            <div class="col-sm">
                                <input type="text" name="name" class="form-control"
                                       value="{{$user->name}}">
                                @error('name')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>

                        </div>


                        <div class="form-group">
                            <label for="task-name" class="col-sm-3 control-label">Email</label>

                            <div class="col-sm">
                                <input type="email" name="email" class="form-control"
                                       value="{{$user->email}}">
                                @error('email')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>

                        </div>
                        <div class="form-group">
                            <label for="task-name" class="col-sm-3 control-label">Phone</label>

                            <div class="col-sm">
                                <input type="text" name="phone" id="task-deadline" class="form-control"
                                       value="{{$user->phone}}">
                            </div>

                        </div>

                        @can('role',Auth::user())
                            <div class="form-group">
                                <label for="task-status" class="col-sm-3 control-label">Role</label>

                                <div class="col-sm">
                                    <select name="role" id="" class="form-control">
                                        <option value="1" @if($user->role == 1) selected @endif>Admin</option>
                                        <option value="0" @if($user->role == 0) selected @endif>Member</option>
                                    </select>
                                </div>
                            </div>
                    @endif



                    <!-- Add Task Button -->
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-6">
                                <button type="submit" class="btn btn-success">
                                    <i class="fa fa-btn fa-plus"></i>Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection