routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('home');
});

Route::group([
    'prefix' => 'categories',
    'middleware' => 'auth',
    'as' => 'category.'
], function () {
    Route::get('', 'CategoryController@index')->name('index');
    Route::get('data', 'CategoryController@getDataCategories')->name('data');
    Route::get('search', 'CategoryController@searchDataCategories')->name('search');
    Route::get('show/{id}', 'CategoryController@show')->name('show');
    Route::get('create', 'CategoryController@create')->name('create');
    Route::post('store', 'CategoryController@store')->name('store');
    Route::get('edit/{id}', 'CategoryController@edit')->name('edit');
    Route::put('update/{id}', 'CategoryController@update')->name('update');
    Route::delete('delete/{id}', 'CategoryController@destroy')->name('destroy');
});


Route::group([
    'prefix' => 'tags',
    'middleware'=>'auth',
    'as' => 'tag.',
],function(){
    route::get('/', 'tagcontroller@index')->name('index'); //hiển thị danh sách tag

    route::get('create', 'tagcontroller@create')->name('create'); //hiển thị form tạo mới 1 tag

    route::post('/', 'tagcontroller@store')->name('store'); //tạo mới tag

    route::get('/show/{id}', 'tagcontroller@show')->name('show'); //hiển thị 1 tag

    route::get('edit/{id}', 'tagcontroller@edit')->name('edit'); //hiển thị form cập nhât 1 tag

    route::get('posts/{id}', 'tagcontroller@posts')->name('posts'); //hiển thị danh sách bài viết


    route::put('/{id}','tagcontroller@update')->name('update'); //cập nhập tag


    route::get('data', 'tagcontroller@getdata')->name('data');


});

Route::group([
    'prefix' => 'posts',
    'as' => 'post.'
], function () {
    Route::get('/', 'PostController@index')->name('index');
    Route::get('create', 'PostController@create')->name('create');
    Route::post('store', 'PostController@store')->name('store');
    Route::get('{id}/edit', 'PostController@edit')->name('edit');
    Route::get('show/{id}', 'PostController@show')->name('show');
    Route::post('update/{id}', 'PostController@update')->name('update');
    Route::delete('delete/{id}', 'PostController@destroy')->name('destroy');
    Route::get('getData', 'PostController@getData')->name('getData');

});


Route::group([
    'middleware' => 'auth',
    'prefix' => 'user',
    'as' => 'user.'
], function () {
    Route::get('/', 'UserController@index')->name('index');
    Route::get('/user-list', 'UserController@user_list')->name('list');
    Route::get('/search', 'UserController@data')->name('data');

    Route::get('create', 'UserController@create')->name('create');
    Route::post('/', 'UserController@store')->name('store');
    Route::put('update/{id}', 'UserController@update')->name('update');
    Route::delete('destroy/{id}', 'UserController@destroy')->name('destroy');
    Route::get('password/{id}', 'UserController@password')->name('password');
    Route::put('change/{id}', 'UserController@change')->name('change');
    Route::get('{id}/edit', 'UserController@edit')->name('edit');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
{{--    <script src="{{ asset('js/app.js') }}" defer></script>--}}

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    @routes()


    <!-- Styles -->
    @yield('css')
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet'
          type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>

    <style>
        ul {
            display: flex;
            margin-bottom: 0px;
        }

        ul li {
            list-style: none;
            margin-right: 5px;
        }
    </style>

    @yield('css')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Home
                </a>

                <ul>
                    <li><a href="{{route('user.index')}}" class="btn">User</a></li>
                    <li><a href="{{route('category.index')}}" class="btn ">Category</a></li>
                    <li><a href="{{route('post.index')}}" class="btn ">Post</a></li>
                    <li><a href="{{route('tag.index')}}" class="btn ">Tags</a></li>
                </ul>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else

                                <a  class="nav-link " href="#"  >
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();" style="margin-top: 4px">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @yield('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

resources/views/layouts/footer.blade.php
<!-- resources/views/layouts/footer.blade.php-->
<hr>
<p>Đây là Footer</p>

resources/views/layouts/header.blade.php
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
                Danh sách công việc
            </a>
        </div>

    </div>
</nav>

resources/views/layouts/master.blade.php
<!-- resources/views/layouts/master.blade.php-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title')</title>
    @yield('css')
</head>
<body id="app-layout">
	<div>
		@yield('header')
	</div>
	<div>
	    @yield('content')
	</div>
		@yield('footer')
	</div>
	@yield('script')
</body>

</html>